const CHARA_DATA = {
    "Banjo & Kazooie": "buddy",
    Bayonetta: "bayonetta",
    Bowser: "koopa",
    "Bowser Jr": "koopajr",
    Byleth: "master",
    "Captain Falcon": "captain",
    Charizard: "plizardon",
    Chrom: "chrom",
    Cloud: "cloud",
    Corrin: "kamui",
    Daisy: "daisy",
    "Dark Pit": "pitb",
    "Dark Samus": "samusd",
    "Diddy Kong": "diddy",
    "Donkey Kong": "donkey",
    "Dr. Mario": "mariod",
    "Duck Hunt": "duckhunt",
    Falco: "falco",
    Fox: "fox",
    Ganondorf: "ganon",
    Greninja: "gekkouga",
    Hero: "brave",
    "Ice Climbers": "ice_climber",
    Ike: "ike",
    Incineroar: "gaogaen",
    Inkling: "inkling",
    Isabelle: "shizue",
    Jigglypuff: "purin",
    Joker: "jack",
    Kazuya: "demon",
    Ken: "ken",
    "King Dedede": "dedede",
    "King K. Rool": "krool",
    Kirby: "kirby",
    Link: "link",
    "Little Mac": "littlemac",
    Lucario: "lucario",
    Lucas: "lucas",
    Lucina: "lucina",
    Luigi: "luigi",
    Mario: "mario",
    Marth: "marth",
    "Mega Man": "rockman",
    "Meta Knight": "metaknight",
    Mewtwo: "mewtwo",
    "Mii Brawler": "miifighter",
    "Mii Gunner": "miigunner",
    "Mii Swordfighter": "miiswordsman",
    "Min-Min": "tantan",
    "Mr. Game & Watch": "gamewatch",
    Mythra: "elight",
    Ness: "ness",
    Olimar: "pikmin",
    "Pac-Man": "pacman",
    Palutena: "palutena",
    Peach: "peach",
    Pichu: "pichu",
    Pikachu: "pikachu",
    "Piranha Plant": "packun",
    Pit: "pit",
    "Pokemon Trainer": "ptrainer",
    Pyra: "eflame",
    "Pyra/Mythra": "pythra",
    Richter: "richter",
    Ridley: "ridley",
    ROB: "robot",
    Robin: "reflet",
    Rosalina: "rosetta",
    Roy: "roy",
    Ryu: "ryu",
    Samus: "samus",
    Sephiroth: "edge",
    Sheik: "sheik",
    Shulk: "shulk",
    Simon: "simon",
    Snake: "snake",
    Sonic: "sonic",
    Sora: "trail",
    Squirtle: "pzenigame",
    Steve: "pickel",
    Terry: "dolly",
    "Toon Link": "toonlink",
    Villager: "murabito",
    Wario: "wario",
    "Wii Fit Trainer": "wiifit",
    Wolf: "wolf",
    Yoshi: "yoshi",
    "Young Link": "younglink",
    Zelda: "zelda",
    "Zero Suit Samus": "szerosuit",
    "Random": "random"
};
